name: flutter_background_location_service
description: A project to run the location track service in background.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_bloc: ^8.1.2
  flutter_local_notifications: ^18.0.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.1
  geolocator: ^13.0.1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
